Commit main and class in  11/01/2022
Savolgan/DataBaseByClass pull request #4
Opened 2022-01-17 17:39 UTC by Savolgan

2022-01-17 18:40 UTC, savichmx requested changes

2022-01-17 18:40 UTC, savichmx commented on src/com/company/model/FootballClub.java
> +    private Integer id_fc;
В джаве поля класса не называются с нижним подчеркиванием. В конкретном случае достаточно поля `id`, но если ты хочешь указать на то что это id именно футбольного клуба, то следует назвать `footballClubId`

2022-01-17 18:40 UTC, savichmx commented on src/com/company/model/FootballClub.java
> +    private String name_fc;
тут тоже

2022-01-17 18:40 UTC, savichmx commented on src/com/company/model/FootballClub.java
> +    private Integer year_birth;
как насчет того, чтобы использовать дату?

2022-01-17 18:40 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer id_p;
тут тоже переименовать

2022-01-17 18:40 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer id_fc;
айди футбольного клуба не нужно, потому что у тебя есть объект FootballClub, который содержит это айди

2022-01-17 18:40 UTC, savichmx commented on src/com/company/repository/FootballClubRepository.java
> +    public void close() throws SQLException {
Интрфейс AutoClosable и этот метод тут не нужны. Представь что ты закроешь Connection в этом месте, а твои другие классы не будут об этом знать и захотят дальше с ним работать. В таком случае произойдет ошибка и они не смогут с ним работать.

2022-01-17 18:40 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +    public void close() throws SQLException {
тут тоже не нужно

2022-01-17 18:40 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +    public void updatePlayer(int id, String name, int age, int id_fc) {
Если есть желание, то можешь его переделать, чтобы он тоже принимал объект Player

2022-01-17 18:47 UTC, Savolgan commented on src/com/company/model/FootballClub.java
> +    private Integer year_birth;
Я дату использовала в Player

2022-01-17 19:10 UTC, savichmx requested changes

2022-01-17 19:10 UTC, savichmx commented on src/com/company/model/FootballClub.java
> +    private Integer idFc;
Сокращать имена типа `Fc` тоже не следует, пиши полностью `footballClubId`

2022-01-17 19:10 UTC, savichmx commented on src/com/company/model/Player.java
> +    private Integer idP;
тут тоже

2022-01-18 21:26 UTC, savichmx commented on src/com/company/repository/PlayerRepository.java
> +            preparedStatement.setInt(3, player.getIdFootballClub());
id должен браться из player.getFootballClub().getId()

2022-01-19 18:28 UTC, savichmx commented on src/com/company/model/Player.java
> +        if (footballClub != null) {
если у тебя поле footballClub == null, это не значит, что не нужно выводить сообщение, это значит, что поле club_name тоже будет null. Например ты можешь сделать так:
`return String.format("Player: id_p = %s,name_p =%s, age =%s, date_of_birth =%s, club_name=%s", idP, nameP, age, dateOfBirth, footballClub != null ? footballClub.getNameFc() : null);`

2022-01-26 08:59 UTC, merged